/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "test.v:1.1-8.10" *)
module test(a, b, c, d, y);
  (* src = "test.v:2.12-2.13" *)
  input a;
  wire a;
  (* src = "test.v:2.15-2.16" *)
  input b;
  wire b;
  (* src = "test.v:2.18-2.19" *)
  input c;
  wire c;
  (* src = "test.v:2.21-2.22" *)
  input d;
  wire d;
  (* src = "test.v:3.12-3.13" *)
  output y;
  wire y;
  (* src = "test.v:2.12-2.13" *)
  wire _00_;
  (* src = "test.v:2.15-2.16" *)
  wire _01_;
  (* src = "test.v:2.18-2.19" *)
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "test.v:3.12-3.13" *)
  wire _05_;
  (* src = "test.v:6.17-6.22" *)
  wire _06_;
  (* src = "test.v:6.27-6.32" *)
  wire _07_;
  (* src = "test.v:6.37-6.42" *)
  wire _08_;
  (* src = "test.v:6.16-6.33" *)
  wire _09_;
  NAND2_X1 _10_ (
    .A1(_02_),
    .A2(_01_),
    .ZN(_03_)
  );
  OAI21_X1 _11_ (
    .A(_00_),
    .B1(_01_),
    .B2(_02_),
    .ZN(_04_)
  );
  NAND2_X1 _12_ (
    .A1(_03_),
    .A2(_04_),
    .ZN(_05_)
  );
  assign y = _05_;
  assign _02_ = c;
  assign _00_ = a;
  assign _01_ = b;
endmodule
