/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 16.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module full_adder(A, B, Cin, Sum, Cout);
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output Sum;
  wire Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  NOR2_X1 _05_ (
    .A1(A),
    .A2(B),
    .ZN(_02_)
  );
  AOI21_X1 _06_ (
    .A(Cin),
    .B1(A),
    .B2(B),
    .ZN(_03_)
  );
  NOR2_X1 _07_ (
    .A1(_02_),
    .A2(_03_),
    .ZN(Cout)
  );
  NOR3_X1 _08_ (
    .A1(Cin),
    .A2(A),
    .A3(B),
    .ZN(_04_)
  );
  AND3_X1 _09_ (
    .A1(Cin),
    .A2(A),
    .A3(B),
    .ZN(_00_)
  );
  INV_X1 _10_ (
    .A(_00_),
    .ZN(_01_)
  );
  OAI21_X1 _11_ (
    .A(_01_),
    .B1(_04_),
    .B2(Cout),
    .ZN(Sum)
  );
endmodule
