/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module rca(A, B, Cin, Sum, Cout);
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  input Cin;
  wire Cin;
  output [15:0] Sum;
  wire [15:0] Sum;
  output Cout;
  wire Cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire \bit_stage[0].fa_inst.A ;
  wire \bit_stage[0].fa_inst.B ;
  wire \bit_stage[0].fa_inst.Cin ;
  wire \bit_stage[0].fa_inst.Sum ;
  wire \bit_stage[10].fa_inst.A ;
  wire \bit_stage[10].fa_inst.B ;
  wire \bit_stage[10].fa_inst.Sum ;
  wire \bit_stage[11].fa_inst.A ;
  wire \bit_stage[11].fa_inst.B ;
  wire \bit_stage[11].fa_inst.Sum ;
  wire \bit_stage[12].fa_inst.A ;
  wire \bit_stage[12].fa_inst.B ;
  wire \bit_stage[12].fa_inst.Sum ;
  wire \bit_stage[13].fa_inst.A ;
  wire \bit_stage[13].fa_inst.B ;
  wire \bit_stage[13].fa_inst.Sum ;
  wire \bit_stage[14].fa_inst.A ;
  wire \bit_stage[14].fa_inst.B ;
  wire \bit_stage[14].fa_inst.Sum ;
  wire \bit_stage[15].fa_inst.A ;
  wire \bit_stage[15].fa_inst.B ;
  wire \bit_stage[15].fa_inst.Cout ;
  wire \bit_stage[15].fa_inst.Sum ;
  wire \bit_stage[1].fa_inst.A ;
  wire \bit_stage[1].fa_inst.B ;
  wire \bit_stage[1].fa_inst.Sum ;
  wire \bit_stage[2].fa_inst.A ;
  wire \bit_stage[2].fa_inst.B ;
  wire \bit_stage[2].fa_inst.Sum ;
  wire \bit_stage[3].fa_inst.A ;
  wire \bit_stage[3].fa_inst.B ;
  wire \bit_stage[3].fa_inst.Sum ;
  wire \bit_stage[4].fa_inst.A ;
  wire \bit_stage[4].fa_inst.B ;
  wire \bit_stage[4].fa_inst.Sum ;
  wire \bit_stage[5].fa_inst.A ;
  wire \bit_stage[5].fa_inst.B ;
  wire \bit_stage[5].fa_inst.Sum ;
  wire \bit_stage[6].fa_inst.A ;
  wire \bit_stage[6].fa_inst.B ;
  wire \bit_stage[6].fa_inst.Sum ;
  wire \bit_stage[7].fa_inst.A ;
  wire \bit_stage[7].fa_inst.B ;
  wire \bit_stage[7].fa_inst.Sum ;
  wire \bit_stage[8].fa_inst.A ;
  wire \bit_stage[8].fa_inst.B ;
  wire \bit_stage[8].fa_inst.Sum ;
  wire \bit_stage[9].fa_inst.A ;
  wire \bit_stage[9].fa_inst.B ;
  wire \bit_stage[9].fa_inst.Sum ;
  wire [16:0] carry;
  NOR2_X4 _082_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_033_)
  );
  AND2_X5 _083_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_034_)
  );
  NOR2_X4 _084_ (
    .A1(Cin),
    .A2(_034_),
    .ZN(_035_)
  );
  \NOR2_X1.5  _085_ (
    .A1(_033_),
    .A2(_035_),
    .ZN(_036_)
  );
  NAND2_X1 _086_ (
    .A1(A[1]),
    .A2(_036_),
    .ZN(_037_)
  );
  \OR2_X2.5  _087_ (
    .A1(A[1]),
    .A2(_036_),
    .ZN(_038_)
  );
  \NAND2_X3.5  _088_ (
    .A1(B[1]),
    .A2(_038_),
    .ZN(_039_)
  );
  NAND2_X2 _089_ (
    .A1(_037_),
    .A2(_039_),
    .ZN(_040_)
  );
  NOR2_X1 _090_ (
    .A1(A[2]),
    .A2(_040_),
    .ZN(_041_)
  );
  \AND2_X3.5  _091_ (
    .A1(A[2]),
    .A2(_040_),
    .ZN(_042_)
  );
  \NOR2_X2.5  _092_ (
    .A1(B[2]),
    .A2(_042_),
    .ZN(_043_)
  );
  \NOR2_X1.5  _093_ (
    .A1(_041_),
    .A2(_043_),
    .ZN(_044_)
  );
  NAND2_X1 _094_ (
    .A1(A[3]),
    .A2(_044_),
    .ZN(_045_)
  );
  \OR2_X2.5  _095_ (
    .A1(A[3]),
    .A2(_044_),
    .ZN(_046_)
  );
  NAND2_X3 _096_ (
    .A1(B[3]),
    .A2(_046_),
    .ZN(_047_)
  );
  NAND2_X2 _097_ (
    .A1(_045_),
    .A2(_047_),
    .ZN(_048_)
  );
  NOR2_X1 _098_ (
    .A1(A[4]),
    .A2(_048_),
    .ZN(_049_)
  );
  \AND2_X3.5  _099_ (
    .A1(A[4]),
    .A2(_048_),
    .ZN(_050_)
  );
  \NOR2_X2.5  _100_ (
    .A1(B[4]),
    .A2(_050_),
    .ZN(_051_)
  );
  \NOR2_X1.5  _101_ (
    .A1(_049_),
    .A2(_051_),
    .ZN(_052_)
  );
  NAND2_X1 _102_ (
    .A1(A[5]),
    .A2(_052_),
    .ZN(_053_)
  );
  \OR2_X2.5  _103_ (
    .A1(A[5]),
    .A2(_052_),
    .ZN(_054_)
  );
  NAND2_X4 _104_ (
    .A1(B[5]),
    .A2(_054_),
    .ZN(_055_)
  );
  NAND2_X2 _105_ (
    .A1(_053_),
    .A2(_055_),
    .ZN(_056_)
  );
  \NOR2_X1.5  _106_ (
    .A1(A[6]),
    .A2(_056_),
    .ZN(_057_)
  );
  AND2_X4 _107_ (
    .A1(A[6]),
    .A2(_056_),
    .ZN(_058_)
  );
  NOR2_X3 _108_ (
    .A1(B[6]),
    .A2(_058_),
    .ZN(_059_)
  );
  NOR2_X1 _109_ (
    .A1(_057_),
    .A2(_059_),
    .ZN(_060_)
  );
  NAND2_X1 _110_ (
    .A1(A[7]),
    .A2(_060_),
    .ZN(_061_)
  );
  \OR2_X2.5  _111_ (
    .A1(A[7]),
    .A2(_060_),
    .ZN(_062_)
  );
  NAND2_X3 _112_ (
    .A1(B[7]),
    .A2(_062_),
    .ZN(_063_)
  );
  NAND2_X2 _113_ (
    .A1(_061_),
    .A2(_063_),
    .ZN(_064_)
  );
  NOR2_X1 _114_ (
    .A1(A[8]),
    .A2(_064_),
    .ZN(_065_)
  );
  \AND2_X3.5  _115_ (
    .A1(A[8]),
    .A2(_064_),
    .ZN(_066_)
  );
  \NOR2_X2.5  _116_ (
    .A1(B[8]),
    .A2(_066_),
    .ZN(_067_)
  );
  \NOR2_X1.5  _117_ (
    .A1(_065_),
    .A2(_067_),
    .ZN(_068_)
  );
  NAND2_X1 _118_ (
    .A1(A[9]),
    .A2(_068_),
    .ZN(_069_)
  );
  \OR2_X2.5  _119_ (
    .A1(A[9]),
    .A2(_068_),
    .ZN(_070_)
  );
  NAND2_X4 _120_ (
    .A1(B[9]),
    .A2(_070_),
    .ZN(_071_)
  );
  NAND2_X2 _121_ (
    .A1(_069_),
    .A2(_071_),
    .ZN(_072_)
  );
  NOR2_X1 _122_ (
    .A1(A[10]),
    .A2(_072_),
    .ZN(_073_)
  );
  \AND2_X3.5  _123_ (
    .A1(A[10]),
    .A2(_072_),
    .ZN(_074_)
  );
  \NOR2_X2.5  _124_ (
    .A1(B[10]),
    .A2(_074_),
    .ZN(_075_)
  );
  \NOR2_X1.5  _125_ (
    .A1(_073_),
    .A2(_075_),
    .ZN(_076_)
  );
  NAND2_X1 _126_ (
    .A1(A[11]),
    .A2(_076_),
    .ZN(_077_)
  );
  \OR2_X2.5  _127_ (
    .A1(A[11]),
    .A2(_076_),
    .ZN(_078_)
  );
  NAND2_X4 _128_ (
    .A1(B[11]),
    .A2(_078_),
    .ZN(_079_)
  );
  NAND2_X2 _129_ (
    .A1(_077_),
    .A2(_079_),
    .ZN(_080_)
  );
  \NOR2_X1.5  _130_ (
    .A1(A[12]),
    .A2(_080_),
    .ZN(_081_)
  );
  AND2_X4 _131_ (
    .A1(A[12]),
    .A2(_080_),
    .ZN(_000_)
  );
  NOR2_X3 _132_ (
    .A1(B[12]),
    .A2(_000_),
    .ZN(_001_)
  );
  NOR2_X1 _133_ (
    .A1(_081_),
    .A2(_001_),
    .ZN(_002_)
  );
  NAND2_X1 _134_ (
    .A1(A[13]),
    .A2(_002_),
    .ZN(_003_)
  );
  \OR2_X2.5  _135_ (
    .A1(A[13]),
    .A2(_002_),
    .ZN(_004_)
  );
  NAND2_X5 _136_ (
    .A1(B[13]),
    .A2(_004_),
    .ZN(_005_)
  );
  NAND2_X3 _137_ (
    .A1(_003_),
    .A2(_005_),
    .ZN(_006_)
  );
  NOR2_X3 _138_ (
    .A1(A[14]),
    .A2(_006_),
    .ZN(_007_)
  );
  AND2_X4 _139_ (
    .A1(A[14]),
    .A2(_006_),
    .ZN(_008_)
  );
  NOR2_X2 _140_ (
    .A1(B[14]),
    .A2(_008_),
    .ZN(_009_)
  );
  NOR2_X1 _141_ (
    .A1(_007_),
    .A2(_009_),
    .ZN(_010_)
  );
  AND2_X2 _142_ (
    .A1(B[15]),
    .A2(_010_),
    .ZN(_011_)
  );
  \NOR2_X1.5  _143_ (
    .A1(B[15]),
    .A2(_010_),
    .ZN(_012_)
  );
  OR2_X5 _144_ (
    .A1(_011_),
    .A2(_012_),
    .ZN(_013_)
  );
  \XNOR2_X3.5  _145_ (
    .A(A[15]),
    .B(_013_),
    .ZN(Sum[15])
  );
  \NOR2_X1.5  _146_ (
    .A1(A[15]),
    .A2(_011_),
    .ZN(_014_)
  );
  NOR2_X1 _147_ (
    .A1(_012_),
    .A2(_014_),
    .ZN(Cout)
  );
  \OR2_X1.5  _148_ (
    .A1(_007_),
    .A2(_008_),
    .ZN(_015_)
  );
  XNOR2_X2 _149_ (
    .A(B[14]),
    .B(_015_),
    .ZN(Sum[14])
  );
  NAND2_X1 _150_ (
    .A1(_003_),
    .A2(_004_),
    .ZN(_016_)
  );
  XNOR2_X1 _151_ (
    .A(B[13]),
    .B(_016_),
    .ZN(Sum[13])
  );
  OR2_X1 _152_ (
    .A1(_081_),
    .A2(_000_),
    .ZN(_017_)
  );
  XNOR2_X1 _153_ (
    .A(B[12]),
    .B(_017_),
    .ZN(Sum[12])
  );
  NAND2_X1 _154_ (
    .A1(_077_),
    .A2(_078_),
    .ZN(_018_)
  );
  XNOR2_X1 _155_ (
    .A(B[11]),
    .B(_018_),
    .ZN(Sum[11])
  );
  OR2_X1 _156_ (
    .A1(_073_),
    .A2(_074_),
    .ZN(_019_)
  );
  XNOR2_X1 _157_ (
    .A(B[10]),
    .B(_019_),
    .ZN(Sum[10])
  );
  NAND2_X1 _158_ (
    .A1(_069_),
    .A2(_070_),
    .ZN(_020_)
  );
  XNOR2_X1 _159_ (
    .A(B[9]),
    .B(_020_),
    .ZN(Sum[9])
  );
  OR2_X1 _160_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_021_)
  );
  XNOR2_X1 _161_ (
    .A(B[8]),
    .B(_021_),
    .ZN(Sum[8])
  );
  NAND2_X1 _162_ (
    .A1(_061_),
    .A2(_062_),
    .ZN(_022_)
  );
  XNOR2_X1 _163_ (
    .A(B[7]),
    .B(_022_),
    .ZN(Sum[7])
  );
  OR2_X1 _164_ (
    .A1(_057_),
    .A2(_058_),
    .ZN(_023_)
  );
  XNOR2_X1 _165_ (
    .A(B[6]),
    .B(_023_),
    .ZN(Sum[6])
  );
  NAND2_X1 _166_ (
    .A1(_053_),
    .A2(_054_),
    .ZN(_024_)
  );
  XNOR2_X1 _167_ (
    .A(B[5]),
    .B(_024_),
    .ZN(Sum[5])
  );
  OR2_X1 _168_ (
    .A1(_049_),
    .A2(_050_),
    .ZN(_025_)
  );
  XNOR2_X1 _169_ (
    .A(B[4]),
    .B(_025_),
    .ZN(Sum[4])
  );
  NAND2_X1 _170_ (
    .A1(_045_),
    .A2(_046_),
    .ZN(_026_)
  );
  XNOR2_X1 _171_ (
    .A(B[3]),
    .B(_026_),
    .ZN(Sum[3])
  );
  OR2_X1 _172_ (
    .A1(_041_),
    .A2(_042_),
    .ZN(_027_)
  );
  XNOR2_X1 _173_ (
    .A(B[2]),
    .B(_027_),
    .ZN(Sum[2])
  );
  NAND2_X1 _174_ (
    .A1(_037_),
    .A2(_038_),
    .ZN(_028_)
  );
  XNOR2_X1 _175_ (
    .A(B[1]),
    .B(_028_),
    .ZN(Sum[1])
  );
  INV_X1 _176_ (
    .A(Cin),
    .ZN(_029_)
  );
  NAND2_X1 _177_ (
    .A1(_029_),
    .A2(_033_),
    .ZN(_030_)
  );
  NAND2_X1 _178_ (
    .A1(Cin),
    .A2(_034_),
    .ZN(_031_)
  );
  NAND2_X1 _179_ (
    .A1(_036_),
    .A2(_031_),
    .ZN(_032_)
  );
  AND2_X1 _180_ (
    .A1(_030_),
    .A2(_032_),
    .ZN(Sum[0])
  );
  assign \bit_stage[10].fa_inst.A  = A[10];
  assign \bit_stage[10].fa_inst.B  = B[10];
  assign \bit_stage[10].fa_inst.Sum  = Sum[10];
  assign \bit_stage[9].fa_inst.A  = A[9];
  assign \bit_stage[9].fa_inst.B  = B[9];
  assign \bit_stage[9].fa_inst.Sum  = Sum[9];
  assign \bit_stage[8].fa_inst.A  = A[8];
  assign \bit_stage[8].fa_inst.B  = B[8];
  assign \bit_stage[8].fa_inst.Sum  = Sum[8];
  assign \bit_stage[7].fa_inst.A  = A[7];
  assign \bit_stage[7].fa_inst.B  = B[7];
  assign \bit_stage[7].fa_inst.Sum  = Sum[7];
  assign \bit_stage[6].fa_inst.A  = A[6];
  assign \bit_stage[6].fa_inst.B  = B[6];
  assign \bit_stage[6].fa_inst.Sum  = Sum[6];
  assign \bit_stage[5].fa_inst.A  = A[5];
  assign \bit_stage[5].fa_inst.B  = B[5];
  assign \bit_stage[5].fa_inst.Sum  = Sum[5];
  assign \bit_stage[15].fa_inst.A  = A[15];
  assign \bit_stage[15].fa_inst.B  = B[15];
  assign \bit_stage[15].fa_inst.Sum  = Sum[15];
  assign \bit_stage[15].fa_inst.Cout  = Cout;
  assign \bit_stage[4].fa_inst.A  = A[4];
  assign \bit_stage[4].fa_inst.B  = B[4];
  assign \bit_stage[11].fa_inst.Sum  = Sum[11];
  assign \bit_stage[4].fa_inst.Sum  = Sum[4];
  assign \bit_stage[14].fa_inst.A  = A[14];
  assign \bit_stage[3].fa_inst.A  = A[3];
  assign \bit_stage[3].fa_inst.B  = B[3];
  assign \bit_stage[3].fa_inst.Sum  = Sum[3];
  assign \bit_stage[14].fa_inst.B  = B[14];
  assign \bit_stage[11].fa_inst.B  = B[11];
  assign \bit_stage[14].fa_inst.Sum  = Sum[14];
  assign \bit_stage[2].fa_inst.A  = A[2];
  assign \bit_stage[2].fa_inst.B  = B[2];
  assign \bit_stage[11].fa_inst.A  = A[11];
  assign \bit_stage[2].fa_inst.Sum  = Sum[2];
  assign \bit_stage[13].fa_inst.A  = A[13];
  assign \bit_stage[13].fa_inst.B  = B[13];
  assign \bit_stage[13].fa_inst.Sum  = Sum[13];
  assign \bit_stage[1].fa_inst.A  = A[1];
  assign \bit_stage[1].fa_inst.B  = B[1];
  assign \bit_stage[1].fa_inst.Sum  = Sum[1];
  assign \bit_stage[12].fa_inst.A  = A[12];
  assign \bit_stage[0].fa_inst.A  = A[0];
  assign \bit_stage[0].fa_inst.B  = B[0];
  assign \bit_stage[0].fa_inst.Cin  = Cin;
  assign \bit_stage[0].fa_inst.Sum  = Sum[0];
  assign \bit_stage[12].fa_inst.B  = B[12];
  assign \bit_stage[12].fa_inst.Sum  = Sum[12];
  assign { carry[16], carry[0] } = { Cout, Cin };
endmodule
