/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module full_adder(A, B, Cin, Sum, Cout);
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output Sum;
  wire Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  \NOR2_X2.5  _07_ (
    .A1(A),
    .A2(B),
    .ZN(_04_)
  );
  AND2_X5 _08_ (
    .A1(A),
    .A2(B),
    .ZN(_05_)
  );
  \NOR2_X3.5  _09_ (
    .A1(Cin),
    .A2(_05_),
    .ZN(_06_)
  );
  NOR2_X5 _10_ (
    .A1(_04_),
    .A2(_06_),
    .ZN(Cout)
  );
  INV_X1 _11_ (
    .A(Cin),
    .ZN(_00_)
  );
  NAND2_X1 _12_ (
    .A1(_00_),
    .A2(_04_),
    .ZN(_01_)
  );
  NAND2_X1 _13_ (
    .A1(Cin),
    .A2(_05_),
    .ZN(_02_)
  );
  NAND2_X2 _14_ (
    .A1(Cout),
    .A2(_02_),
    .ZN(_03_)
  );
  \AND2_X3.5  _15_ (
    .A1(_01_),
    .A2(_03_),
    .ZN(Sum)
  );
endmodule
