/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module full_adder(A, B, Cin, Sum, Cout);
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output Sum;
  wire Sum;
  output Cout;
  wire Cout;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  NAND2_X4 _4_ (
    .A1(A),
    .A2(B),
    .ZN(_1_)
  );
  OAI21_X4 _5_ (
    .A(Cin),
    .B1(A),
    .B2(B),
    .ZN(_2_)
  );
  NAND2_X4 _6_ (
    .A1(_1_),
    .A2(_2_),
    .ZN(Cout)
  );
  INV_X1 _7_ (
    .A(Cin),
    .ZN(_3_)
  );
  NOR3_X2 _8_ (
    .A1(Cin),
    .A2(A),
    .A3(B),
    .ZN(_0_)
  );
  OAI22_X4 _9_ (
    .A1(_3_),
    .A2(_1_),
    .B1(Cout),
    .B2(_0_),
    .ZN(Sum)
  );
endmodule
